spring:
  cloud:
    stream:
      bindings:
        videos-to-analyse-subscription:
          destination: videos-to-analyse-production
        analysed-videos-topic:
          destination: analysed-videos-production
        analysed-video-ids-topic:
          destination: analysed-video-ids-production
        analysed-video-ids-subscription:
          destination: analysed-video-ids-production
