spring:
  cloud:
    stream:
      bindings:
        videos-to-analyse:
          group: video-analyser
  security:
    user:
      name: jacek
      password: jacek

logging:
  level:
    org.springframework.security: DEBUG
