spring:
  cloud:
    stream:
      bindings:
        videos-to-analyse-subscription:
          destination: videos-to-analyse-testing
        analysed-videos-topic:
          destination: analysed-videos-testing
        analysed-video-ids-topic:
          destination: analysed-video-ids-testing
        analysed-video-ids-subscription:
          destination: analysed-video-ids-testing
