spring:
  cloud:
    stream:
      bindings:
        videos-to-analyse:
          destination: videos-to-analyse-staging
        analysed-videos:
          destination: analysed-videos-staging
        analysed-video-ids-topic:
          destination: analysed-video-ids-staging
        analysed-video-ids-subscription:
          destination: analysed-video-ids-staging
