logging:
  config: "classpath:logback-json.xml"

spring:
  cloud:
    gcp:
      pubsub:
        subscriber:
          executor-threads: 1
          max-ack-extension-period: 60

pubsub:
  consumerGroup: video-analyser
